# Generated by Django 3.1.14 on 2023-04-26 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_auto_20230426_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='difficluty',
            new_name='difficulty',
        ),
    ]
